Traceback (most recent call last):
  File "<ipython-input-5-4dca3ff47df1>", line 2, in <module>
    raise Exception('This is the error messgage.')
Exception: This is the error messgage.
